### ISSUE TITLE
Company XMLIDs in CSV files

### ISSUE THREAD

**Issue by grindtildeath** [camptocamp/odoo-dj#28]
When the setup is done in a multicompany environment, the company XMLID in CSV files is generated from res.company aka field whereas it should use the existing company XMLID as it is in the songs.

Accounting song example (XMLID is the one already existing in DB `'__setup__.company_labs_lux'`) : 
```
@anthem.log
def account_config_settings(ctx):
    """ Setup account.config.settings """
    model = ctx.env['account.config.settings'].with_context({'tracking_disable':1})
    model.create({
        ...
        # Société  # noqa
        'company_id': ctx.env.ref('__setup__.company_labs_lux').id,
        ....
    }).execute()
```

account.tax CSV Example (XMLID is a new one generated from res.company aka `"__setup__.res_company_etix_labs_s_a_r_l"`) :
```
"id","account_id/id","amount","amount_type","children_tax_ids/id","description","name","price_include","refund_account_id/id","sequence","type_tax_use","company_id/id"
"__setup__.etix_labs_account_tax_achat_suede_6","__setup__.etix_labs_account_account_vat_receivable_sweden","6.0","percent","","A-SW-6","Achat Suède (6%)","False","__setup__.etix_labs_account_account_vat_receivable_sweden","1","purchase","__setup__.res_company_etix_labs_s_a_r_l"
```

**Comment by simahawk** [comment]
@grindtildeath this is actually  reality since a while. Now we have also tests on dev branch https://github.com/camptocamp/odoo-dj/commit/5c1826b5a24cac43f0603b3d7fe59ee2ac3f0184

**Comment by simahawk** [comment]
merged
