### ISSUE TITLE
Handle file fields within transient models (use case: sale.config.settings)

### ISSUE THREAD

**Issue by leemannd** [camptocamp/odoo-dj#94]
When exporting `sale.config.setting` we faced 2 issues:
 - field `sale_note` should be moved to an html file
 - special fields export is actually not working w/ transient models

You'll find WIP => [here](https://github.com/leemannd/odoo-prototype/tree/add_dj_sale)

**Comment by simahawk** [comment]
back on this: I'm not even sure if we should export such fields in any case. Example:
```bash
odoo/src/addons/sale/models/res_config_settings.py:12:    sale_note = fields.Text(related='company_id.sale_note', string="Terms & Conditions")
```
as you see that field is stored on the company itself which we should export anyway...
Relates to #101

**Comment by simahawk** [comment]
export settings deprecated
