### ISSUE TITLE
res.partner and res.users export must exclude admin and some fields

### ISSUE THREAD

**Issue by leemannd** [camptocamp/odoo-dj#97]
We have to exclude a fiew things from `.csv` export files related to `res.partner` & `res.users`:
 - password_crypt field 
 - user/partner admin records (!!!)
 - signature (especially if there is only `<p><br/<p/>` it make going wild `anthem songs.install.mts.crm::main` wich contains a relation to a user_id

**Comment by simahawk** [comment]
solved and tested in dev branch

**Comment by simahawk** [comment]
merged
