### ISSUE TITLE
PEP8 - generated songs don't fit standards

### ISSUE THREAD

**Issue by leemannd** [camptocamp/odoo-dj#98]
Generated songs don't fit PEP8 standard.
We should either don't test PEP8 on these files because we use them as generated files and overwrite them. Or make them PEP8 Compliant

**Comment by leemannd** [comment]
@guewen I like the idea of autopep8. I don't really need to read/edit those files and for them I already use autopep8 without any complains (since now).

**Comment by simahawk** [comment]
yeah, I'll try that
